// Janto Phone - Localization System (TR/EN)
const translations = {
  tr: {
    // System
    'system.boot': 'Başlatılıyor...',
    'system.swipeToUnlock': 'Açmak için yukarı kaydırın',
    'system.enterPasscode': 'Şifreyi girin',
    'system.faceId': 'Face ID',
    'system.cancel': 'İptal',
    'system.delete': 'Sil',
    'system.done': 'Bitti',
    'system.edit': 'Düzenle',
    'system.back': 'Geri',
    'system.search': 'Ara',
    'system.save': 'Kaydet',
    'system.send': 'Gönder',
    'system.ok': 'Tamam',
    'system.yes': 'Evet',
    'system.no': 'Hayır',
    'system.close': 'Kapat',
    'system.add': 'Ekle',
    'system.remove': 'Kaldır',
    'system.reset': 'Sıfırla',
    'system.emergency': 'Acil Durum',
    'system.charging': 'Şarj oluyor',
    'system.lowBattery': 'Düşük Pil',
    'system.powerOff': 'Kapat',
    'system.today': 'Bugün',
    'system.yesterday': 'Dün',
    'system.notifications': 'Bildirimler',
    'system.noNotifications': 'Bildirim yok',
    'system.clearAll': 'Tümünü temizle',
    'system.copied': 'Kopyalandı',

    // Days
    'day.monday': 'Pazartesi',
    'day.tuesday': 'Salı',
    'day.wednesday': 'Çarşamba',
    'day.thursday': 'Perşembe',
    'day.friday': 'Cuma',
    'day.saturday': 'Cumartesi',
    'day.sunday': 'Pazar',

    // Months
    'month.january': 'Ocak',
    'month.february': 'Şubat',
    'month.march': 'Mart',
    'month.april': 'Nisan',
    'month.may': 'Mayıs',
    'month.june': 'Haziran',
    'month.july': 'Temmuz',
    'month.august': 'Ağustos',
    'month.september': 'Eylül',
    'month.october': 'Ekim',
    'month.november': 'Kasım',
    'month.december': 'Aralık',

    // Home
    'home.editMode': 'Düzenleme Modu',
    'home.addWidget': 'Widget Ekle',
    'home.searchApps': 'Uygulama Ara',

    // Settings
    'settings.title': 'Ayarlar',
    'settings.account': 'Hesap',
    'settings.accountName': 'Janto Hesabı',
    'settings.profile': 'Profil',
    'settings.passwordSecurity': 'Şifre ve Güvenlik',
    'settings.paymentShipping': 'Ödeme ve Kargo',
    'settings.icloud': 'iCloud',
    'settings.mediaPurchases': 'Medya ve Satın Alma',
    'settings.findMy': 'Bul',
    'settings.airplaneMode': 'Uçak Modu',
    'settings.bluetooth': 'Bluetooth',
    'settings.wifi': 'Wi-Fi',
    'settings.cellular': 'Hücresel',
    'settings.cellularData': 'Hücresel Veri',
    'settings.notifications': 'Bildirimler',
    'settings.soundsHaptics': 'Sesler ve Dokunsal',
    'settings.screenTime': 'Ekran Süresi',
    'settings.general': 'Genel',
    'settings.controlCenter': 'Denetim Merkezi',
    'settings.displayBrightness': 'Ekran ve Parlaklık',
    'settings.theme': 'Tema',
    'settings.iconPack': 'İkon Paketi',
    'settings.wallpaper': 'Duvar Kağıdı',
    'settings.case': 'Kılıf',
    'settings.language': 'Dil',
    'settings.accessibility': 'Erişilebilirlik',
    'settings.help': 'Yardım',
    'settings.about': 'Hakkında',
    'settings.terms': 'Koşullar',
    'settings.privacy': 'Gizlilik',
    'settings.uploadQuality': 'Yükleme Kalitesi',
    'settings.darkMode': 'Karanlık Mod',
    'settings.lightMode': 'Aydınlık Mod',
    'settings.auto': 'Otomatik',
    'settings.turkish': 'Türkçe',
    'settings.english': 'İngilizce',
    'settings.on': 'Açık',
    'settings.off': 'Kapalı',
    'settings.connected': 'Bağlı',
    'settings.notConnected': 'Bağlı değil',
    'settings.version': 'Sürüm',
    'settings.storage': 'Depolama',
    'settings.previewPolicy': 'Önizleme Politikası',
    'settings.always': 'Her Zaman',
    'settings.whenUnlocked': 'Kilit Açıkken',
    'settings.never': 'Asla',
    'settings.hdPhoto': 'HD Fotoğraf Modu',
    'settings.screenTimeTitle': 'Ekran Süresi',
    'settings.dailyAverage': 'Günlük Ortalama',
    'settings.mostUsed': 'En Çok Kullanılan',
    'settings.pickups': 'Kaldırmalar',

    // Music
    'music.title': 'Müzik',
    'music.welcome': 'Hoş geldiniz',
    'music.trending': 'Trend',
    'music.forYou': 'Sizin İçin',
    'music.categories': 'Kategoriler',
    'music.search': 'Müzik Ara',
    'music.library': 'Kütüphane',
    'music.liked': 'Beğenilenler',
    'music.playlists': 'Çalma Listeleri',
    'music.nowPlaying': 'Şu An Çalıyor',
    'music.queue': 'Sıra',
    'music.shuffle': 'Karıştır',
    'music.repeat': 'Tekrarla',
    'music.pop': 'Pop',
    'music.rock': 'Rock',
    'music.hiphop': 'Hip-Hop',
    'music.electronic': 'Elektronik',
    'music.jazz': 'Caz',
    'music.classical': 'Klasik',

    // Garage
    'garage.title': 'Garaj',
    'garage.vehicles': 'Araçlar',
    'garage.totalVehicles': 'Toplam Araç',
    'garage.stored': 'Depoda',
    'garage.out': 'Dışarıda',
    'garage.impounded': 'Çekilmiş',
    'garage.junkyard': 'Çöplük',
    'garage.callVehicle': 'Aracı Çağır',
    'garage.showOnMap': 'Haritada Göster',
    'garage.fuel': 'Yakıt',
    'garage.engine': 'Motor',
    'garage.body': 'Kaporta',
    'garage.statistics': 'İstatistikler',
    'garage.distanceHistory': 'Mesafe Geçmişi',
    'garage.insuranceHistory': 'Sigorta Geçmişi',
    'garage.vehicleCalled': 'Araç çağrıldı',
    'garage.refresh': 'Yenile',
    'garage.status': 'Durum',
    'garage.plate': 'Plaka',

    // Messages
    'messages.title': 'Mesajlar',
    'messages.newMessage': 'Yeni Mesaj',
    'messages.typeMessage': 'Mesaj yazın...',
    'messages.voiceMessage': 'Sesli Mesaj',
    'messages.location': 'Konum',
    'messages.contactCard': 'Kişi Kartı',
    'messages.today': 'Bugün',
    'messages.read': 'Okundu',
    'messages.delivered': 'İletildi',

    // WhisApp
    'whisapp.title': 'WhisApp',
    'whisapp.chats': 'Sohbetler',
    'whisapp.groups': 'Gruplar',
    'whisapp.community': 'Topluluk',
    'whisapp.status': 'Durum',
    'whisapp.calls': 'Aramalar',
    'whisapp.online': 'Çevrimiçi',
    'whisapp.typing': 'yazıyor...',
    'whisapp.liveLocation': 'Canlı Konum',
    'whisapp.archived': 'Arşivlenmiş',
    'whisapp.muted': 'Sessize alındı',
    'whisapp.blocked': 'Engellendi',
    'whisapp.groupInfo': 'Grup Bilgisi',
    'whisapp.chatInfo': 'Sohbet Bilgisi',
    'whisapp.members': 'Üyeler',
    'whisapp.media': 'Medya',
    'whisapp.sharedLocation': 'Paylaşılan Konum',
    'whisapp.reply': 'Yanıtla',
    'whisapp.forward': 'İlet',
    'whisapp.react': 'Tepki',

    // Vibeshot
    'vibeshot.title': 'Vibeshot',
    'vibeshot.feed': 'Akış',
    'vibeshot.explore': 'Keşfet',
    'vibeshot.reels': 'Reels',
    'vibeshot.profile': 'Profil',
    'vibeshot.editProfile': 'Profili Düzenle',
    'vibeshot.posts': 'Gönderiler',
    'vibeshot.followers': 'Takipçiler',
    'vibeshot.following': 'Takip',
    'vibeshot.follow': 'Takip Et',
    'vibeshot.unfollow': 'Takibi Bırak',
    'vibeshot.like': 'Beğen',
    'vibeshot.comment': 'Yorum',
    'vibeshot.share': 'Paylaş',
    'vibeshot.save': 'Kaydet',
    'vibeshot.comments': 'Yorumlar',
    'vibeshot.addComment': 'Yorum ekle...',
    'vibeshot.login': 'Giriş Yap',
    'vibeshot.signup': 'Kayıt Ol',
    'vibeshot.username': 'Kullanıcı Adı',
    'vibeshot.password': 'Şifre',
    'vibeshot.email': 'E-posta',
    'vibeshot.verify': 'Doğrula',
    'vibeshot.verificationCode': 'Doğrulama Kodu',
    'vibeshot.success': 'Başarılı',
    'vibeshot.welcomeBack': 'Tekrar hoş geldiniz',
    'vibeshot.createAccount': 'Hesap Oluştur',
    'vibeshot.alreadyHaveAccount': 'Zaten hesabınız var mı?',
    'vibeshot.dontHaveAccount': 'Hesabınız yok mu?',
    'vibeshot.settingsPrivacy': 'Ayarlar ve Gizlilik',
    'vibeshot.privacy': 'Gizlilik',
    'vibeshot.blockedAccounts': 'Engellenen Hesaplar',
    'vibeshot.passwordSecurity': 'Şifre ve Güvenlik',
    'vibeshot.faceId': 'Face ID',
    'vibeshot.language': 'Dil',
    'vibeshot.storyArchive': 'Hikaye Arşivi',
    'vibeshot.newPost': 'Yeni Gönderi',
    'vibeshot.story': 'Hikaye',
    'vibeshot.privateAccount': 'Gizli Hesap',
    'vibeshot.publicAccount': 'Herkese Açık',
    'vibeshot.notifications': 'Bildirimler',
    'vibeshot.likes': 'beğeni',

    // Bank
    'bank.title': 'Banka',
    'bank.accounts': 'Hesaplar',
    'bank.personal': 'Kişisel',
    'bank.job': 'İş',
    'bank.shared': 'Ortak',
    'bank.transfer': 'Transfer',
    'bank.recipients': 'Alıcılar',
    'bank.bills': 'Faturalar',
    'bank.history': 'Geçmiş',
    'bank.balance': 'Bakiye',
    'bank.iban': 'IBAN',
    'bank.copyIban': 'IBAN Kopyala',
    'bank.ibanCopied': 'IBAN kopyalandı',
    'bank.amount': 'Tutar',
    'bank.recipient': 'Alıcı',
    'bank.description': 'Açıklama',
    'bank.sendMoney': 'Para Gönder',
    'bank.payBill': 'Fatura Öde',
    'bank.payAll': 'Tümünü Öde',
    'bank.registeredRecipients': 'Kayıtlı Alıcılar',
    'bank.transactionSuccess': 'Transfer başarılı',
    'bank.transactionFailed': 'Transfer başarısız',
    'bank.insufficientFunds': 'Yetersiz bakiye',
    'bank.income': 'Gelir',
    'bank.expense': 'Gider',

    // Maps
    'maps.title': 'Haritalar',
    'maps.sharedLocation': 'Paylaşılan Konum',
    'maps.destination': 'Varış Noktası',
    'maps.navigate': 'Yol Tarifi',
    'maps.yourLocation': 'Konumunuz',

    // Emergency
    'emergency.title': 'Acil Durum',
    'emergency.report': 'Bildir',
    'emergency.police': 'Polis',
    'emergency.ambulance': 'Ambulans',
    'emergency.fire': 'İtfaiye',
    'emergency.callNow': 'Şimdi Ara',
    'emergency.sendLocation': 'Konum Gönder',
    'emergency.confirmation': 'Onay',
    'emergency.reportSent': 'Bildirim gönderildi',
    'emergency.callEmergency': 'Acil Arama',

    // Gallery
    'gallery.title': 'Galeri',
    'gallery.photos': 'Fotoğraflar',
    'gallery.videos': 'Videolar',
    'gallery.albums': 'Albümler',
    'gallery.allPhotos': 'Tüm Fotoğraflar',

    // Camera
    'camera.title': 'Kamera',
    'camera.photo': 'Fotoğraf',
    'camera.video': 'Video',
    'camera.portrait': 'Portre',
    'camera.capture': 'Çek',

    // Notes
    'notes.title': 'Notlar',
    'notes.newNote': 'Yeni Not',
    'notes.folders': 'Klasörler',
    'notes.allNotes': 'Tüm Notlar',

    // Calendar
    'calendar.title': 'Takvim',
    'calendar.events': 'Etkinlikler',
    'calendar.newEvent': 'Yeni Etkinlik',
    'calendar.noEvents': 'Etkinlik yok',

    // V Store
    'vstore.title': 'V Store',
    'vstore.apps': 'Uygulamalar',
    'vstore.featured': 'Öne Çıkanlar',
    'vstore.install': 'Yükle',
    'vstore.installed': 'Yüklendi',
    'vstore.update': 'Güncelle',

    // Vault
    'vault.title': 'Kasa',
    'vault.storage': 'Depolama',
    'vault.backups': 'Yedekler',
    'vault.encrypted': 'Şifrelenmiş',
    'vault.lastBackup': 'Son Yedekleme',

    // Battery
    'battery.title': 'Pil',
    'battery.level': 'Pil Seviyesi',
    'battery.health': 'Pil Sağlığı',
    'battery.lowPower': 'Düşük Güç Modu',
    'battery.charging': 'Şarj Oluyor',
    'battery.powerbank': 'Powerbank',
    'battery.powerbankLevel': 'Powerbank Seviyesi',
    'battery.timeRemaining': 'Kalan Süre',
    'battery.usageSince': 'Son şarjdan bu yana kullanım',

    // Call
    'call.incoming': 'Gelen Arama',
    'call.outgoing': 'Giden Arama',
    'call.accept': 'Kabul Et',
    'call.reject': 'Reddet',
    'call.end': 'Bitir',
    'call.mute': 'Sessiz',
    'call.speaker': 'Hoparlör',
    'call.video': 'Video',
    'call.calling': 'Aranıyor...',
    'call.busy': 'Meşgul',
    'call.minimize': 'Küçült',

    // Playground
    'playground.title': 'Demo Oyun Alanı',
    'playground.selectApp': 'Uygulama Seç',
    'playground.scenario': 'Senaryo',
    'playground.reset': 'Sıfırla',
    'playground.darkMode': 'Karanlık Mod',
    'playground.lightMode': 'Aydınlık Mod',
    'playground.sendNotification': 'Bildirim Gönder',
    'playground.incomingCall': 'Gelen Arama',
    'playground.battery': 'Pil',
    'playground.charge': 'Şarj',
    'playground.currentApp': 'Mevcut Uygulama',
    'playground.currentRoute': 'Mevcut Rota',
    'playground.state': 'Durum',
  },

  en: {
    // System
    'system.boot': 'Starting...',
    'system.swipeToUnlock': 'Swipe up to unlock',
    'system.enterPasscode': 'Enter passcode',
    'system.faceId': 'Face ID',
    'system.cancel': 'Cancel',
    'system.delete': 'Delete',
    'system.done': 'Done',
    'system.edit': 'Edit',
    'system.back': 'Back',
    'system.search': 'Search',
    'system.save': 'Save',
    'system.send': 'Send',
    'system.ok': 'OK',
    'system.yes': 'Yes',
    'system.no': 'No',
    'system.close': 'Close',
    'system.add': 'Add',
    'system.remove': 'Remove',
    'system.reset': 'Reset',
    'system.emergency': 'Emergency',
    'system.charging': 'Charging',
    'system.lowBattery': 'Low Battery',
    'system.powerOff': 'Power Off',
    'system.today': 'Today',
    'system.yesterday': 'Yesterday',
    'system.notifications': 'Notifications',
    'system.noNotifications': 'No notifications',
    'system.clearAll': 'Clear All',
    'system.copied': 'Copied',

    // Days
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wednesday': 'Wednesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',
    'day.sunday': 'Sunday',

    // Months
    'month.january': 'January',
    'month.february': 'February',
    'month.march': 'March',
    'month.april': 'April',
    'month.may': 'May',
    'month.june': 'June',
    'month.july': 'July',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'October',
    'month.november': 'November',
    'month.december': 'December',

    // Home
    'home.editMode': 'Edit Mode',
    'home.addWidget': 'Add Widget',
    'home.searchApps': 'Search Apps',

    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.accountName': 'Janto Account',
    'settings.profile': 'Profile',
    'settings.passwordSecurity': 'Password & Security',
    'settings.paymentShipping': 'Payment & Shipping',
    'settings.icloud': 'iCloud',
    'settings.mediaPurchases': 'Media & Purchases',
    'settings.findMy': 'Find My',
    'settings.airplaneMode': 'Airplane Mode',
    'settings.bluetooth': 'Bluetooth',
    'settings.wifi': 'Wi-Fi',
    'settings.cellular': 'Cellular',
    'settings.cellularData': 'Cellular Data',
    'settings.notifications': 'Notifications',
    'settings.soundsHaptics': 'Sounds & Haptics',
    'settings.screenTime': 'Screen Time',
    'settings.general': 'General',
    'settings.controlCenter': 'Control Center',
    'settings.displayBrightness': 'Display & Brightness',
    'settings.theme': 'Theme',
    'settings.iconPack': 'Icon Pack',
    'settings.wallpaper': 'Wallpaper',
    'settings.case': 'Case',
    'settings.language': 'Language',
    'settings.accessibility': 'Accessibility',
    'settings.help': 'Help',
    'settings.about': 'About',
    'settings.terms': 'Terms',
    'settings.privacy': 'Privacy',
    'settings.uploadQuality': 'Upload Quality',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.auto': 'Auto',
    'settings.turkish': 'Turkish',
    'settings.english': 'English',
    'settings.on': 'On',
    'settings.off': 'Off',
    'settings.connected': 'Connected',
    'settings.notConnected': 'Not Connected',
    'settings.version': 'Version',
    'settings.storage': 'Storage',
    'settings.previewPolicy': 'Preview Policy',
    'settings.always': 'Always',
    'settings.whenUnlocked': 'When Unlocked',
    'settings.never': 'Never',
    'settings.hdPhoto': 'HD Photo Mode',
    'settings.screenTimeTitle': 'Screen Time',
    'settings.dailyAverage': 'Daily Average',
    'settings.mostUsed': 'Most Used',
    'settings.pickups': 'Pickups',

    // Music
    'music.title': 'Music',
    'music.welcome': 'Welcome',
    'music.trending': 'Trending',
    'music.forYou': 'For You',
    'music.categories': 'Categories',
    'music.search': 'Search Music',
    'music.library': 'Library',
    'music.liked': 'Liked',
    'music.playlists': 'Playlists',
    'music.nowPlaying': 'Now Playing',
    'music.queue': 'Queue',
    'music.shuffle': 'Shuffle',
    'music.repeat': 'Repeat',
    'music.pop': 'Pop',
    'music.rock': 'Rock',
    'music.hiphop': 'Hip-Hop',
    'music.electronic': 'Electronic',
    'music.jazz': 'Jazz',
    'music.classical': 'Classical',

    // Garage
    'garage.title': 'Garage',
    'garage.vehicles': 'Vehicles',
    'garage.totalVehicles': 'Total Vehicles',
    'garage.stored': 'Stored',
    'garage.out': 'Out',
    'garage.impounded': 'Impounded',
    'garage.junkyard': 'Junkyard',
    'garage.callVehicle': 'Call Vehicle',
    'garage.showOnMap': 'Show on Map',
    'garage.fuel': 'Fuel',
    'garage.engine': 'Engine',
    'garage.body': 'Body',
    'garage.statistics': 'Statistics',
    'garage.distanceHistory': 'Distance History',
    'garage.insuranceHistory': 'Insurance History',
    'garage.vehicleCalled': 'Vehicle called',
    'garage.refresh': 'Refresh',
    'garage.status': 'Status',
    'garage.plate': 'Plate',

    // Messages
    'messages.title': 'Messages',
    'messages.newMessage': 'New Message',
    'messages.typeMessage': 'Type a message...',
    'messages.voiceMessage': 'Voice Message',
    'messages.location': 'Location',
    'messages.contactCard': 'Contact Card',
    'messages.today': 'Today',
    'messages.read': 'Read',
    'messages.delivered': 'Delivered',

    // WhisApp
    'whisapp.title': 'WhisApp',
    'whisapp.chats': 'Chats',
    'whisapp.groups': 'Groups',
    'whisapp.community': 'Community',
    'whisapp.status': 'Status',
    'whisapp.calls': 'Calls',
    'whisapp.online': 'Online',
    'whisapp.typing': 'typing...',
    'whisapp.liveLocation': 'Live Location',
    'whisapp.archived': 'Archived',
    'whisapp.muted': 'Muted',
    'whisapp.blocked': 'Blocked',
    'whisapp.groupInfo': 'Group Info',
    'whisapp.chatInfo': 'Chat Info',
    'whisapp.members': 'Members',
    'whisapp.media': 'Media',
    'whisapp.sharedLocation': 'Shared Location',
    'whisapp.reply': 'Reply',
    'whisapp.forward': 'Forward',
    'whisapp.react': 'React',

    // Vibeshot
    'vibeshot.title': 'Vibeshot',
    'vibeshot.feed': 'Feed',
    'vibeshot.explore': 'Explore',
    'vibeshot.reels': 'Reels',
    'vibeshot.profile': 'Profile',
    'vibeshot.editProfile': 'Edit Profile',
    'vibeshot.posts': 'Posts',
    'vibeshot.followers': 'Followers',
    'vibeshot.following': 'Following',
    'vibeshot.follow': 'Follow',
    'vibeshot.unfollow': 'Unfollow',
    'vibeshot.like': 'Like',
    'vibeshot.comment': 'Comment',
    'vibeshot.share': 'Share',
    'vibeshot.save': 'Save',
    'vibeshot.comments': 'Comments',
    'vibeshot.addComment': 'Add a comment...',
    'vibeshot.login': 'Log In',
    'vibeshot.signup': 'Sign Up',
    'vibeshot.username': 'Username',
    'vibeshot.password': 'Password',
    'vibeshot.email': 'Email',
    'vibeshot.verify': 'Verify',
    'vibeshot.verificationCode': 'Verification Code',
    'vibeshot.success': 'Success',
    'vibeshot.welcomeBack': 'Welcome back',
    'vibeshot.createAccount': 'Create Account',
    'vibeshot.alreadyHaveAccount': 'Already have an account?',
    'vibeshot.dontHaveAccount': "Don't have an account?",
    'vibeshot.settingsPrivacy': 'Settings & Privacy',
    'vibeshot.privacy': 'Privacy',
    'vibeshot.blockedAccounts': 'Blocked Accounts',
    'vibeshot.passwordSecurity': 'Password & Security',
    'vibeshot.faceId': 'Face ID',
    'vibeshot.language': 'Language',
    'vibeshot.storyArchive': 'Story Archive',
    'vibeshot.newPost': 'New Post',
    'vibeshot.story': 'Story',
    'vibeshot.privateAccount': 'Private Account',
    'vibeshot.publicAccount': 'Public',
    'vibeshot.notifications': 'Notifications',
    'vibeshot.likes': 'likes',

    // Bank
    'bank.title': 'Bank',
    'bank.accounts': 'Accounts',
    'bank.personal': 'Personal',
    'bank.job': 'Job',
    'bank.shared': 'Shared',
    'bank.transfer': 'Transfer',
    'bank.recipients': 'Recipients',
    'bank.bills': 'Bills',
    'bank.history': 'History',
    'bank.balance': 'Balance',
    'bank.iban': 'IBAN',
    'bank.copyIban': 'Copy IBAN',
    'bank.ibanCopied': 'IBAN copied',
    'bank.amount': 'Amount',
    'bank.recipient': 'Recipient',
    'bank.description': 'Description',
    'bank.sendMoney': 'Send Money',
    'bank.payBill': 'Pay Bill',
    'bank.payAll': 'Pay All',
    'bank.registeredRecipients': 'Registered Recipients',
    'bank.transactionSuccess': 'Transfer successful',
    'bank.transactionFailed': 'Transfer failed',
    'bank.insufficientFunds': 'Insufficient funds',
    'bank.income': 'Income',
    'bank.expense': 'Expense',

    // Maps
    'maps.title': 'Maps',
    'maps.sharedLocation': 'Shared Location',
    'maps.destination': 'Destination',
    'maps.navigate': 'Navigate',
    'maps.yourLocation': 'Your Location',

    // Emergency
    'emergency.title': 'Emergency',
    'emergency.report': 'Report',
    'emergency.police': 'Police',
    'emergency.ambulance': 'Ambulance',
    'emergency.fire': 'Fire Dept.',
    'emergency.callNow': 'Call Now',
    'emergency.sendLocation': 'Send Location',
    'emergency.confirmation': 'Confirmation',
    'emergency.reportSent': 'Report sent',
    'emergency.callEmergency': 'Emergency Call',

    // Gallery
    'gallery.title': 'Gallery',
    'gallery.photos': 'Photos',
    'gallery.videos': 'Videos',
    'gallery.albums': 'Albums',
    'gallery.allPhotos': 'All Photos',

    // Camera
    'camera.title': 'Camera',
    'camera.photo': 'Photo',
    'camera.video': 'Video',
    'camera.portrait': 'Portrait',
    'camera.capture': 'Capture',

    // Notes
    'notes.title': 'Notes',
    'notes.newNote': 'New Note',
    'notes.folders': 'Folders',
    'notes.allNotes': 'All Notes',

    // Calendar
    'calendar.title': 'Calendar',
    'calendar.events': 'Events',
    'calendar.newEvent': 'New Event',
    'calendar.noEvents': 'No events',

    // V Store
    'vstore.title': 'V Store',
    'vstore.apps': 'Apps',
    'vstore.featured': 'Featured',
    'vstore.install': 'Install',
    'vstore.installed': 'Installed',
    'vstore.update': 'Update',

    // Vault
    'vault.title': 'Vault',
    'vault.storage': 'Storage',
    'vault.backups': 'Backups',
    'vault.encrypted': 'Encrypted',
    'vault.lastBackup': 'Last Backup',

    // Battery
    'battery.title': 'Battery',
    'battery.level': 'Battery Level',
    'battery.health': 'Battery Health',
    'battery.lowPower': 'Low Power Mode',
    'battery.charging': 'Charging',
    'battery.powerbank': 'Powerbank',
    'battery.powerbankLevel': 'Powerbank Level',
    'battery.timeRemaining': 'Time Remaining',
    'battery.usageSince': 'Usage since last charge',

    // Call
    'call.incoming': 'Incoming Call',
    'call.outgoing': 'Outgoing Call',
    'call.accept': 'Accept',
    'call.reject': 'Reject',
    'call.end': 'End',
    'call.mute': 'Mute',
    'call.speaker': 'Speaker',
    'call.video': 'Video',
    'call.calling': 'Calling...',
    'call.busy': 'Busy',
    'call.minimize': 'Minimize',

    // Playground
    'playground.title': 'Demo Playground',
    'playground.selectApp': 'Select App',
    'playground.scenario': 'Scenario',
    'playground.reset': 'Reset',
    'playground.darkMode': 'Dark Mode',
    'playground.lightMode': 'Light Mode',
    'playground.sendNotification': 'Send Notification',
    'playground.incomingCall': 'Incoming Call',
    'playground.battery': 'Battery',
    'playground.charge': 'Charge',
    'playground.currentApp': 'Current App',
    'playground.currentRoute': 'Current Route',
    'playground.state': 'State',
  }
}

function repairMojibake(value) {
  if (typeof value !== "string") return value
  if (!/[ÃÅÄâğ]/.test(value)) return value
  try {
    return decodeURIComponent(escape(value))
  } catch {
    return value
  }
}

export function t(key, lang = 'tr') {
  const value = translations[lang]?.[key] || translations.en?.[key] || key
  return repairMojibake(value)
}

export function readLocalized(value, lang = 'tr', fallback = '') {
  if (value && typeof value === 'object') {
    const resolved = value[lang] || value.en || fallback
    return repairMojibake(resolved)
  }
  if (typeof value === 'string') {
    return repairMojibake(value)
  }
  return fallback
}

export function getTranslations(lang) {
  return translations[lang] || translations.en
}

export default translations
